<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UserService.Domain\UserService.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\HireHub.Contracts\HireHub.Contracts.csproj" />
  </ItemGroup>

</Project>
